// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkG0K4afbPOxJBvrRbVjRzo65a_a3iIZU',
    appId: '1:494757030271:web:b7e980de7274625fe8924a',
    messagingSenderId: '494757030271',
    projectId: 'taskly-7daa8',
    authDomain: 'taskly-7daa8.firebaseapp.com',
    storageBucket: 'taskly-7daa8.firebasestorage.app',
    measurementId: 'G-PE4MVMYJN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgIl_n1DKiNA5b6LoV16ppT1TTyI2xyRU',
    appId: '1:494757030271:android:35c562d52bc50b63e8924a',
    messagingSenderId: '494757030271',
    projectId: 'taskly-7daa8',
    storageBucket: 'taskly-7daa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbNXdtGBME1T27RhNVEOteYW9omTvKD0A',
    appId: '1:494757030271:ios:b43fd73d3c691145e8924a',
    messagingSenderId: '494757030271',
    projectId: 'taskly-7daa8',
    storageBucket: 'taskly-7daa8.firebasestorage.app',
    iosBundleId: 'com.example.taskly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbNXdtGBME1T27RhNVEOteYW9omTvKD0A',
    appId: '1:494757030271:ios:b43fd73d3c691145e8924a',
    messagingSenderId: '494757030271',
    projectId: 'taskly-7daa8',
    storageBucket: 'taskly-7daa8.firebasestorage.app',
    iosBundleId: 'com.example.taskly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkG0K4afbPOxJBvrRbVjRzo65a_a3iIZU',
    appId: '1:494757030271:web:84c069f6285eaf96e8924a',
    messagingSenderId: '494757030271',
    projectId: 'taskly-7daa8',
    authDomain: 'taskly-7daa8.firebaseapp.com',
    storageBucket: 'taskly-7daa8.firebasestorage.app',
    measurementId: 'G-GS65Y1TVN4',
  );
}
